site_name: 'Lorian Documentation'
site_description: 'Welcome to the Lorian documentation'
site_author: 'Tforcum'
site_url: 'https://docs.deadinc.xyz'
repo_name: 'Lorian-docs'
repo_url: 'https://github.com/Tslimshady99/lorian-docs'
edit_uri: edit/master/docs/
remote_branch: gh-pages
copyright: 'Copyright © 2020 Tforcum, Lorian, Bot Dev. "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'blue'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc
  - footnotes

plugins:
    - search

nav:
  - Home: 'index.md'
  - Commands:
    - Command Reference: 'commands.md'
    - Planed Commands: 'commandsplaned.md'

