site_name: 'Lorian Documentation'
site_description: 'Welcome to the Lorian documentation'
site_author: 'Tforcum'
site_url: 'https://docs.tforcum.me'
repo_name: 'Lorian-bot/docs'
repo_url: 'https://github.com/lorian-bot/docs'
edit_uri: edit/master/docs/
remote_branch: gh-pages
copyright: 'Copyright © 2018 Tforcum, Lorian, Bot Dev. "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'
theme: 'material'
extra:
  feature:
    tabs: true
  logo: '/docs/img/logo.png'
  palette:
    primary: 'grey'
    accent: 'red'
  font:
    text: 'Droid Sans'
    font: 'Droid Sans Mono'
  social:
    - type: 'github'
      link: 'https://github.com/lorian-bot'

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc
plugins:
    - search
pages:
  - Home: 'index.md'
