site_name: 'Lorian Documentation'
site_description: 'Welcome to the Lorian documentation'
site_author: 'Tforcum'
site_url: 'https://lorian.deadinc.xyz'
repo_name: 'Lorian-bot/docs'
repo_url: 'https://github.com/Tslimshady99/lorian'
edit_uri: edit/master/docs/
remote_branch: gh-pages
copyright: 'Copyright © 2018 Tforcum, Lorian, Bot Dev. "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'
theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'red'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc

plugins:
    - search

nav:
  - Home: 'index.md'
  - Commands:
    - Command Reference: 'commands.md'
    - Custom Commands: 'custom_commands.md'

