site_name: 'Lorian Documentation'
site_description: 'Welcome to the Lorian documentation'
site_author: 'Tforcum'
site_url: 'https://docs.tforcum.me'
repo_name: 'Lorian-bot/docs'
repo_url: 'https://github.com/lorian-bot/docs'
edit_uri: edit/master/docs/
remote_branch: gh-pages
copyright: 'Copyright © 2018 Tforcum, Lorian, Bot Dev. "Discord", "Discord App", and any associated logos are registered trademarks of Hammer & Chisel, inc.'
theme:
  name: 'material'
  palette:
    primary: 'grey'
    accent: 'red'
  feature:
    tabs: true

markdown_extensions:
  - admonition
  - meta
  - codehilite
  - toc

plugins:
    - search

pages:
  - Home: 'index.md'
  - Commands:
    - Command Reference: 'commands.md'
    - Custom Commands: 'custom_commands.md'
  - Emojis:
    - Guild Emotes: 'emojis/guild-emojis.md'
    - Emoji Servers:
      - List: 'emojis/serverlist.md'
      - servers:
        - Lorian: 'emojis/servers/bd-lorian.md'
        - Main: 'emojis/servers/emoji-main.md'
        - Material: 'emojis/servers/emoji-material.md'
        - Random: 'emojis/servers/emoji-random.md'
        - Random 2: 'emojis/servers/emoji-random2.md'
        - Animals: 'emojis/servers/emoji-animals.md'
        - Weapons: 'emojis/servers/emoji-weapons.md'
        - Money: 'emojis/servers/emoji-money.md'
        - CatBlob: 'emojis/servers/emoji-catblob.md'
        - CatBlob 2: 'emojis/servers/emoji-catblob2.md'
        - CatBlob 3: 'emojis/servers/emoji-catblob3.md'
        - CatBlob 4: 'emojis/servers/emoji-catblob4.md'
        - Kat: 'emojis/servers/emoji-kat.md'
        - Blobs: 'emojis/servers/emoji-blobs.md'
        - Blobs 2: 'emojis/servers/emoji-blobs2.md'
