ersion: 2

jobs:
  docs-build-test:
    docker:
      - image: anthonyz/python3-node8:latest
    steps:
      - checkout
      - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
      - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt

  docs-deploy:
    docker:
      - image: anthonyz/python3-node8:latest
    steps:
      - checkout
      - run:
          name: Register Python alias for compatibility
          command: alias python='python3'
      - run:
          name: Install Python dependencies
          command: python3 -m pip install --upgrade -r requirements.txt
      - add_ssh_keys:
          fingerprints:
              - "11:01:09:3e:22:0e:f3:8e:9a:33:3e:e7:8c:7c:aa:94"
      - run:
          name: Deploy docs
          command: |
            git config user.email 25397933+Tslimshady99@users.noreply.github.com
            python3 -m mkdocs gh-deploy
workflows:
  version: 2
  docs:
    jobs:
      - docs-build-test
      - docs-deploy:
          requires:
            - docs-build-test
          filters:
            branches:
              only: master
